// Exports:
export const SUBTITLES = [
  "How's life?",
  "How's it going?",
  "What's going on?",
  "How's your day going?",
  "How are you doing?",
  "How are things?",
  "Hope you've been doing good!",
  "What have you been up to lately?",
  "Everything good?",
  "Things have been weird lately..",
  "Stay safe out there!",
  "Remember to exercise!",
  "Remember to eat healthy!",
  "Remember to have a good sleep schedule.",
  "Remember to drink more water! 🥤",
  "Remember to chill out sometimes!",
  "Not everything is in your control, but how you react to external things is.",
  "Remember to be strong and remember those who love you.",
  "Remember to appreciate the sky!",
  "How's the water? 🌊",
  "Take a moment to remember if you're forgetting something!",
  "Don't be pressurized into consuming more and more.",
  "Take a moment to appreciate the game of existence!",
  "Don't let social media use you!",
  "[ R E D A C T E D ]",
  "[ EXPUNGED ]",
  "[ COPYRIGHT STRIKED ]",
  "Watch out for the [REDACTED] following you!",
  "Where there are rocks, watch out!",
  "Cottleston, Cottleston, Cottleston Pie..",
  "A fly can't bird, but a bird can fly!",
  "Ask me a riddle and I reply..",
  "\"Rabbit's clever,\" said Pooh thoughtfully. \"I suppose that that's why he never understands anything.\"",
  "The wise are not learned; the learned are not wise.",
  "A well-frog cannot imagine the ocean.",
  "A summer insect cannot conceive of ice.",
  "What does Crustimoney Proseedcake mean?",
  "\"I laugh at his poems, as he laughs at mine. They read like the words of a blind man, describing the sun.\"",
  "Now is it true, or is it not — that what is which and which is what?",
  "Hardly anybody knows, if those are these or these are those.",
  "I sometimes wonder if it's true, that who is what and what is who.",
  "How very readily one sees, that these are whose — but whose are these?",
  "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
  "Never pretend to a love which you do not actually feel, for love is not ours to command.",
  "No valid plans for the future can be made by those who have no capacity for living now.",
  "You don't look out there for God, something in the sky, you look in you.",
  "Muddy water is best cleared by leaving it alone.",
  "When you swim you don't grab hold of the water, because if you do you will sink and drown. Instead you relax, and float.",
  "You are an aperture through which the universe is looking at and exploring itself.",
  "The menu is not the meal.",
  "The more a thing tends to be permanent, the more it tends to be lifeless.",
  "Problems that remain persistently insoluble should always be suspected as questions asked in the wrong way.",
  "What we have forgotten is that thoughts and words are conventions, and that it is fatal to take conventions too seriously.",
  "The one who loves all intensely, begins perceiving in all living beings a part of himself.",
  "The human body is the temple of God. One who kindles the light of awareness within gets true light.",
  "Look to this day, for it is life, the very breath of life.",
  "For yesterday is only a dream, and tomorrow is but a vision. But today, well lived.",
  "Set your heart upon your work, but never on its reward.",
  "You came here empty-handed, and you will leave empty-handed.",
  "You are not slain when the body is slain.",
  "We behold what we are, and we are what we behold.",
  "> app unrelated",
  "> ohno.png",
  "> be me",
  "> imagine unironically reading this",
  "ayo logang what's popping",
  "The little space within the heart is as great as the vast universe.",
  "Dreams are real as long as they last. Can we say more of life?",
  "You Are That.",
  "He who is rich in the knowledge of the Self does not covet external power or possession.",
  "There is enough in the world for everyone’s need; there is not enough for everyone’s greed.",
  "When will the iron age end?",
];
